/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartmentRequest } from '../../models/department-request';
import { DepartmentResponse } from '../../models/department-response';

export interface Create12$Params {
      body: DepartmentRequest
}

export function create12(http: HttpClient, rootUrl: string, params: Create12$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartmentResponse>> {
  const rb = new RequestBuilder(rootUrl, create12.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartmentResponse>;
    })
  );
}

create12.PATH = '/department';
