/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartmentResponse } from '../../models/department-response';

export interface Get9$Params {
  id: number;
}

export function get9(http: HttpClient, rootUrl: string, params: Get9$Params, context?: HttpContext): Observable<StrictHttpResponse<DepartmentResponse>> {
  const rb = new RequestBuilder(rootUrl, get9.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DepartmentResponse>;
    })
  );
}

get9.PATH = '/department/{id}';
