/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemResponse } from '../../models/item-response';

export interface ChangeStatus2$Params {
  id: number;
}

export function changeStatus2(http: HttpClient, rootUrl: string, params: ChangeStatus2$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponse>> {
  const rb = new RequestBuilder(rootUrl, changeStatus2.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemResponse>;
    })
  );
}

changeStatus2.PATH = '/item/change-status/{id}';
