/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemRequest } from '../../models/item-request';
import { ItemResponse } from '../../models/item-response';

export interface Create10$Params {
      body: ItemRequest
}

export function create10(http: HttpClient, rootUrl: string, params: Create10$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponse>> {
  const rb = new RequestBuilder(rootUrl, create10.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemResponse>;
    })
  );
}

create10.PATH = '/item';
