/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PermissionRequest } from '../../models/permission-request';
import { PermissionResponse } from '../../models/permission-response';

export interface Update7$Params {
  id: number;
      body: PermissionRequest
}

export function update7(http: HttpClient, rootUrl: string, params: Update7$Params, context?: HttpContext): Observable<StrictHttpResponse<PermissionResponse>> {
  const rb = new RequestBuilder(rootUrl, update7.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PermissionResponse>;
    })
  );
}

update7.PATH = '/permission/{id}';
