/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApprovePurchaseOrderRequest } from '../../models/approve-purchase-order-request';
import { PurchaseOrderResponse } from '../../models/purchase-order-response';

export interface ApprovePurchaseOrder$Params {
      body: ApprovePurchaseOrderRequest
}

export function approvePurchaseOrder(http: HttpClient, rootUrl: string, params: ApprovePurchaseOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseOrderResponse>> {
  const rb = new RequestBuilder(rootUrl, approvePurchaseOrder.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseOrderResponse>;
    })
  );
}

approvePurchaseOrder.PATH = '/purchase/order/approve';
