/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseOrderResponse } from '../../models/purchase-order-response';

export interface ClearPurchaseOrder$Params {
  id: number;
}

export function clearPurchaseOrder(http: HttpClient, rootUrl: string, params: ClearPurchaseOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseOrderResponse>> {
  const rb = new RequestBuilder(rootUrl, clearPurchaseOrder.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseOrderResponse>;
    })
  );
}

clearPurchaseOrder.PATH = '/purchase/order/clear/{id}';
