/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseOrderResponse } from '../../models/purchase-order-response';
import { ReceivePurchaseOrderRequest } from '../../models/receive-purchase-order-request';

export interface FinishPurchaseOrder$Params {
      body: ReceivePurchaseOrderRequest
}

export function finishPurchaseOrder(http: HttpClient, rootUrl: string, params: FinishPurchaseOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseOrderResponse>> {
  const rb = new RequestBuilder(rootUrl, finishPurchaseOrder.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseOrderResponse>;
    })
  );
}

finishPurchaseOrder.PATH = '/purchase/order/receive';
