/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseOrderResponse } from '../../models/purchase-order-response';

export interface GetAllByStatus$Params {
  status: 'PENDING' | 'VETTED' | 'APPROVED' | 'CLEARED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
}

export function getAllByStatus(http: HttpClient, rootUrl: string, params: GetAllByStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchaseOrderResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllByStatus.PATH, 'get');
  if (params) {
    rb.path('status', params.status, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PurchaseOrderResponse>>;
    })
  );
}

getAllByStatus.PATH = '/purchase/order/status/{status}';
