/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseItemRequest } from '../../models/purchase-item-request';
import { PurchaseItemResponse } from '../../models/purchase-item-response';

export interface Create6$Params {
      body: PurchaseItemRequest
}

export function create6(http: HttpClient, rootUrl: string, params: Create6$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseItemResponse>> {
  const rb = new RequestBuilder(rootUrl, create6.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseItemResponse>;
    })
  );
}

create6.PATH = '/purchase/item';
