/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnitResponse } from '../../models/unit-response';

export interface GetDepartment$Params {
  id: number;
}

export function getDepartment(http: HttpClient, rootUrl: string, params: GetDepartment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UnitResponse>>> {
  const rb = new RequestBuilder(rootUrl, getDepartment.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UnitResponse>>;
    })
  );
}

getDepartment.PATH = '/unit/department/{id}';
