/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RoleResponse } from '../../models/role-response';

export interface DetachRole$Params {
  roleId: number;
  permissionId: number;
}

export function detachRole(http: HttpClient, rootUrl: string, params: DetachRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
  const rb = new RequestBuilder(rootUrl, detachRole.PATH, 'patch');
  if (params) {
    rb.path('roleId', params.roleId, {});
    rb.path('permissionId', params.permissionId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RoleResponse>;
    })
  );
}

detachRole.PATH = '/role/detach/role/{roleId}/permission/{permissionId}';
