/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserApiApiService } from './services/user-api-api.service';
import { UnitApiApiService } from './services/unit-api-api.service';
import { UnitOfMeasureApiApiService } from './services/unit-of-measure-api-api.service';
import { SupplierApiApiService } from './services/supplier-api-api.service';
import { StoreApiApiService } from './services/store-api-api.service';
import { RoleApiApiService } from './services/role-api-api.service';
import { PurchaseQuotationApiApiService } from './services/purchase-quotation-api-api.service';
import { PurchaseItemApiApiService } from './services/purchase-item-api-api.service';
import { PermissionApiApiService } from './services/permission-api-api.service';
import { ItemApiApiService } from './services/item-api-api.service';
import { ItemCategoryControllerApiService } from './services/item-category-controller-api.service';
import { DepartmentApiApiService } from './services/department-api-api.service';
import { BankAccountApiApiService } from './services/bank-account-api-api.service';
import { PurchaseOrderApiApiService } from './services/purchase-order-api-api.service';
import { ProductionOrderApiApiService } from './services/production-order-api-api.service';
import { ProductionInputItemApiApiService } from './services/production-input-item-api-api.service';
import { FileUploadControllerApiService } from './services/file-upload-controller-api.service';
import { AuthenticationApiApiService } from './services/authentication-api-api.service';
import { PurchasePaymentApiApiService } from './services/purchase-payment-api-api.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UserApiApiService,
    UnitApiApiService,
    UnitOfMeasureApiApiService,
    SupplierApiApiService,
    StoreApiApiService,
    RoleApiApiService,
    PurchaseQuotationApiApiService,
    PurchaseItemApiApiService,
    PermissionApiApiService,
    ItemApiApiService,
    ItemCategoryControllerApiService,
    DepartmentApiApiService,
    BankAccountApiApiService,
    PurchaseOrderApiApiService,
    ProductionOrderApiApiService,
    ProductionInputItemApiApiService,
    FileUploadControllerApiService,
    AuthenticationApiApiService,
    PurchasePaymentApiApiService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
