/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchasePaymentResponse } from '../../models/purchase-payment-response';

export interface GetByPurchaseOrderPayment$Params {
  purchaseOrderPaymentId: number;
}

export function getByPurchaseOrderPayment(http: HttpClient, rootUrl: string, params: GetByPurchaseOrderPayment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchasePaymentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getByPurchaseOrderPayment.PATH, 'get');
  if (params) {
    rb.path('purchaseOrderPaymentId', params.purchaseOrderPaymentId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PurchasePaymentResponse>>;
    })
  );
}

getByPurchaseOrderPayment.PATH = '/purchase-payment/{purchaseOrderPaymentId}';
