/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchasePaymentResponse } from '../../models/purchase-payment-response';

export interface GetAll11$Params {
}

export function getAll11(http: HttpClient, rootUrl: string, params?: GetAll11$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchasePaymentResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAll11.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PurchasePaymentResponse>>;
    })
  );
}

getAll11.PATH = '/';
