/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionItemRequest } from '../../models/production-item-request';
import { ProductionItemResponse } from '../../models/production-item-response';

export interface Create8$Params {
      body: ProductionItemRequest
}

export function create8(http: HttpClient, rootUrl: string, params: Create8$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductionItemResponse>> {
  const rb = new RequestBuilder(rootUrl, create8.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductionItemResponse>;
    })
  );
}

create8.PATH = '/production/input-item';
