/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionItemResponse } from '../../models/production-item-response';

export interface Get14$Params {
  id: number;
}

export function get14(http: HttpClient, rootUrl: string, params: Get14$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductionItemResponse>> {
  const rb = new RequestBuilder(rootUrl, get14.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductionItemResponse>;
    })
  );
}

get14.PATH = '/production/input-item/{id}';
