/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionItemResponse } from '../../models/production-item-response';

export interface GetAllByProductionOrder$Params {
  id: number;
}

export function getAllByProductionOrder(http: HttpClient, rootUrl: string, params: GetAllByProductionOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductionItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAllByProductionOrder.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductionItemResponse>>;
    })
  );
}

getAllByProductionOrder.PATH = '/production/input-item/order/{id}';
