/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemCategoryRequest } from '../../models/item-category-request';
import { ItemCategoryResponse } from '../../models/item-category-response';

export interface Create11$Params {
      body: ItemCategoryRequest
}

export function create11(http: HttpClient, rootUrl: string, params: Create11$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, create11.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemCategoryResponse>;
    })
  );
}

create11.PATH = '/item-category';
