/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemCategoryResponse } from '../../models/item-category-response';

export interface Get8$Params {
  id: number;
}

export function get8(http: HttpClient, rootUrl: string, params: Get8$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, get8.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemCategoryResponse>;
    })
  );
}

get8.PATH = '/item-category/{id}';
