/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemCategoryResponse } from '../../models/item-category-response';

export interface GetAll8$Params {
}

export function getAll8(http: HttpClient, rootUrl: string, params?: GetAll8$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemCategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getAll8.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ItemCategoryResponse>>;
    })
  );
}

getAll8.PATH = '/item-category';
