/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BankAccountRequest {
  accountName: string;
  accountNumber: number;
  bankName: string;
}
