/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BankAccountResponse {
  accountName?: string;
  accountNumber?: number;
  active?: boolean;
  bankName?: string;
  createdAt?: string;
  id?: number;
  updatedAt?: string;
}
