/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DepartmentResponse {
  departmentHeadFirstName?: string;
  departmentHeadId?: number;
  departmentHeadLastName?: string;
  id?: number;
  name?: string;
}
