/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductionItemRequest } from '../models/production-item-request';
export interface FinishProductionRequest {
  items: Array<ProductionItemRequest>;
}
