/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemRequest {
  isExpirable: boolean;
  itemCategoryId: number;
  itemType: 'RAW' | 'RESALABLE' | 'FINISHED';
  name: string;
  unitOfMeasureId: number;
}
