/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemCategoryResponse } from '../models/item-category-response';
import { UnitOfMeasureResponse } from '../models/unit-of-measure-response';
export interface ItemResponse {
  createdAt?: string;
  id?: number;
  isActive?: boolean;
  isExpirable?: boolean;
  itemCategory?: ItemCategoryResponse;
  itemCode?: string;
  itemType?: 'RAW' | 'RESALABLE' | 'FINISHED';
  name?: string;
  unitOfMeasure?: UnitOfMeasureResponse;
  updatedAt?: string;
}
