/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductionItemRequest {
  expirationDate?: string;
  itemId?: number;
  productionOrderId?: number;
  quantity?: number;
}
