/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductionItemResponse } from '../models/production-item-response';
import { UnitResponse } from '../models/unit-response';
import { UserResponse } from '../models/user-response';
export interface ProductionOrderResponse {
  approvedAt?: string;
  approvedBy?: UserResponse;
  createdAt?: string;
  createdBy?: UserResponse;
  finishedAt?: string;
  finishedBy?: UserResponse;
  id?: number;
  inputItems?: Array<ProductionItemResponse>;
  outputItems?: Array<ProductionItemResponse>;
  status?: 'PENDING' | 'VETTED' | 'APPROVED' | 'CLEARED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
  unit?: UnitResponse;
  updatedAt?: string;
  vettedAt?: string;
  vettedBy?: UserResponse;
}
