/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchasePaymentRequest {
  accountId?: number;
  amount: number;
  paymentMethod?: 'CASH' | 'TRANSFER' | 'POS';
  purchaseOrderPaymentId: number;
}
