/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchasePaymentResponse } from '../models/purchase-payment-response';
export interface PurchaseOrderPaymentResponse {
  balance?: number;
  createdAt?: string;
  id?: number;
  purchaseOrderId?: number;
  purchasePayments?: Array<PurchasePaymentResponse>;
  totalAmountPaid?: number;
  totalAmountPayable?: number;
  updatedAt?: string;
}
