/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ItemResponse } from '../models/item-response';
export interface PurchaseItemResponse {
  id?: number;
  item?: ItemResponse;
  quantity?: number;
  quantityDamaged?: number;
  quantityReceived?: number;
  totalPrice?: number;
  unitPrice?: number;
}
