/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseItemResponse } from '../models/purchase-item-response';
import { PurchaseOrderPaymentResponse } from '../models/purchase-order-payment-response';
import { PurchaseQuotationResponse } from '../models/purchase-quotation-response';
import { UnitResponse } from '../models/unit-response';
import { UserResponse } from '../models/user-response';
export interface PurchaseOrderResponse {
  approvedBy?: UserResponse;
  clearedBy?: UserResponse;
  createdBy?: UserResponse;
  discountAmount?: number;
  discountType?: 'AMOUNT' | 'PERCENTAGE';
  discountValue?: number;
  id?: number;
  items?: Array<PurchaseItemResponse>;
  orderDate?: string;
  orderPayment?: PurchaseOrderPaymentResponse;
  paidBy?: UserResponse;
  quotations?: Array<PurchaseQuotationResponse>;
  status?: 'PENDING' | 'VETTED' | 'APPROVED' | 'CLEARED' | 'REJECTED' | 'CANCELLED' | 'COMPLETED';
  subTotal?: number;
  tax?: number;
  taxRate?: number;
  totalAmount?: number;
  unit?: UnitResponse;
  updatedAt?: string;
  vettedBy?: UserResponse;
}
