/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseItemRequest {
  itemId: number;
  purchaseOrderId?: number;
  quantity: number;
  unitPrice: number;
}
