/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PurchaseItemRequest } from '../models/purchase-item-request';
import { PurchaseQuotationRequest } from '../models/purchase-quotation-request';
export interface PurchaseOrderRequest {
  items?: Array<PurchaseItemRequest>;
  quotations?: Array<PurchaseQuotationRequest>;
}
