/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupplierResponse } from '../models/supplier-response';
import { UserResponse } from '../models/user-response';
export interface PurchaseQuotationResponse {
  amount?: number;
  createdAt?: string;
  createdBy?: UserResponse;
  id?: number;
  invoiceUrl?: string;
  quotationNumber?: string;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED' | 'EXPIRED' | 'ORDERED';
  supplier?: SupplierResponse;
  updatedAt?: string;
}
