/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseQuotationRequest {
  amount: number;
  invoiceFile?: Blob;
  purchaseOrderId: number;
  supplierId: number;
}
