/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccountResponse } from '../models/bank-account-response';
import { UserResponse } from '../models/user-response';
export interface PurchasePaymentResponse {
  account?: BankAccountResponse;
  amount?: number;
  id?: number;
  paidBy?: UserResponse;
  paymentDate?: string;
  purchaseOrderPaymentId?: number;
}
