/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReceivePurchaseOrderItemRequest } from '../models/receive-purchase-order-item-request';
export interface ReceivePurchaseOrderRequest {
  purchaseOrderId?: number;
  receiveItems?: Array<ReceivePurchaseOrderItemRequest>;
}
