/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionResponse } from '../models/permission-response';
export interface RoleResponse {
  id?: number;
  permissions?: Array<PermissionResponse>;
  roleName?: string;
}
