/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UnitResponse } from '../models/unit-response';
export interface StoreResponse {
  createdAt?: string;
  id?: number;
  location?: string;
  name?: string;
  storeType?: 'PRIMARY' | 'SECONDARY';
  unit?: UnitResponse;
  updatedAt?: string;
}
