/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StoreRequest {
  location: string;
  name: string;
  storeType: 'PRIMARY' | 'SECONDARY';
  unitId: number;
}
