/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupplierResponse {
  active?: boolean;
  address?: string;
  createdAt?: string;
  email?: string;
  id?: number;
  name?: string;
  phone?: string;
  updatedAt?: string;
}
