/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupplierRequest {
  address: string;
  email?: string;
  name: string;
  phone: string;
}
