/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UnitRequest {
  address: string;
  departmentId: number;
  description: string;
  name: string;
  unitHeadId?: number;
}
