/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  address: string;
  email: string;
  firstName: string;
  lastName: string;
  middleName?: string;
  password: string;
  phone: string;
  roleId?: number;
  unitId: number;
  username: string;
}
