/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleResponse } from '../models/role-response';
import { UnitResponse } from '../models/unit-response';
export interface UserResponse {
  accountExpired?: boolean;
  accountLocked?: boolean;
  address?: string;
  credentialsExpired?: boolean;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  id?: number;
  lastName?: string;
  middleName?: string;
  phone?: string;
  roles?: Array<RoleResponse>;
  unit?: UnitResponse;
  username?: string;
}
