/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { attachRole } from '../fn/role-api/attach-role';
import { AttachRole$Params } from '../fn/role-api/attach-role';
import { createRole } from '../fn/role-api/create-role';
import { CreateRole$Params } from '../fn/role-api/create-role';
import { deleteRole } from '../fn/role-api/delete-role';
import { DeleteRole$Params } from '../fn/role-api/delete-role';
import { detachRole } from '../fn/role-api/detach-role';
import { DetachRole$Params } from '../fn/role-api/detach-role';
import { getAllRoles } from '../fn/role-api/get-all-roles';
import { GetAllRoles$Params } from '../fn/role-api/get-all-roles';
import { getRole } from '../fn/role-api/get-role';
import { GetRole$Params } from '../fn/role-api/get-role';
import { RoleResponse } from '../models/role-response';
import { updateRole } from '../fn/role-api/update-role';
import { UpdateRole$Params } from '../fn/role-api/update-role';


/**
 * Manages Role Endpoints
 */
@Injectable({ providedIn: 'root' })
export class RoleApiApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getRole()` */
  static readonly GetRolePath = '/role/{id}';

  /**
   * Gets a Role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRole$Response(params: GetRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return getRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets a Role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRole(params: GetRole$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.getRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

  /** Path part for operation `updateRole()` */
  static readonly UpdateRolePath = '/role/{id}';

  /**
   * Updates new Role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRole$Response(params: UpdateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return updateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates new Role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateRole(params: UpdateRole$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.updateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

  /** Path part for operation `deleteRole()` */
  static readonly DeleteRolePath = '/role/{id}';

  /**
   * Deletes new Role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRole$Response(params: DeleteRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes new Role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteRole(params: DeleteRole$Params, context?: HttpContext): Observable<void> {
    return this.deleteRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllRoles()` */
  static readonly GetAllRolesPath = '/role';

  /**
   * Gets all Roles.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles$Response(params?: GetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponse>>> {
    return getAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all Roles.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles(params?: GetAllRoles$Params, context?: HttpContext): Observable<Array<RoleResponse>> {
    return this.getAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleResponse>>): Array<RoleResponse> => r.body)
    );
  }

  /** Path part for operation `createRole()` */
  static readonly CreateRolePath = '/role';

  /**
   * Creates new Role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRole$Response(params: CreateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return createRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates new Role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createRole(params: CreateRole$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.createRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

  /** Path part for operation `detachRole()` */
  static readonly DetachRolePath = '/role/detach/role/{roleId}/permission/{permissionId}';

  /**
   * Detach permission to role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `detachRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  detachRole$Response(params: DetachRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return detachRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Detach permission to role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `detachRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  detachRole(params: DetachRole$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.detachRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

  /** Path part for operation `attachRole()` */
  static readonly AttachRolePath = '/role/attach/role/{roleId}/permission/{permissionId}';

  /**
   * Attach permission to role.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachRole$Response(params: AttachRole$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return attachRole(this.http, this.rootUrl, params, context);
  }

  /**
   * Attach permission to role.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachRole(params: AttachRole$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.attachRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

}
