/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductionOrderResponse } from '../../models/production-order-response';

export interface DispenseInputItems$Params {
  id: number;
}

export function dispenseInputItems(http: HttpClient, rootUrl: string, params: DispenseInputItems$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductionOrderResponse>> {
  const rb = new RequestBuilder(rootUrl, dispenseInputItems.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductionOrderResponse>;
    })
  );
}

dispenseInputItems.PATH = '/production/order/dispense/{id}';
