/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseQuotationRequest } from '../../models/purchase-quotation-request';
import { PurchaseQuotationResponse } from '../../models/purchase-quotation-response';

export interface CreateBulk$Params {
      body?: Array<PurchaseQuotationRequest>
}

export function createBulk(http: HttpClient, rootUrl: string, params?: CreateBulk$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PurchaseQuotationResponse>>> {
  const rb = new RequestBuilder(rootUrl, createBulk.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PurchaseQuotationResponse>>;
    })
  );
}

createBulk.PATH = '/purchase/quotation/bulk';
