/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupplierResponse } from '../../models/supplier-response';

export interface ChangeStatus$Params {
  id: number;
}

export function changeStatus(http: HttpClient, rootUrl: string, params: ChangeStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<SupplierResponse>> {
  const rb = new RequestBuilder(rootUrl, changeStatus.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupplierResponse>;
    })
  );
}

changeStatus.PATH = '/supplier/{id}';
