/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupplierRequest } from '../../models/supplier-request';
import { SupplierResponse } from '../../models/supplier-response';

export interface Create3$Params {
      body: SupplierRequest
}

export function create3(http: HttpClient, rootUrl: string, params: Create3$Params, context?: HttpContext): Observable<StrictHttpResponse<SupplierResponse>> {
  const rb = new RequestBuilder(rootUrl, create3.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupplierResponse>;
    })
  );
}

create3.PATH = '/supplier';
