/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BankAccountResponse } from '../../models/bank-account-response';

export interface Get10$Params {
  id: number;
}

export function get10(http: HttpClient, rootUrl: string, params: Get10$Params, context?: HttpContext): Observable<StrictHttpResponse<BankAccountResponse>> {
  const rb = new RequestBuilder(rootUrl, get10.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BankAccountResponse>;
    })
  );
}

get10.PATH = '/bank-account/{id}';
