/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BankAccountRequest } from '../../models/bank-account-request';
import { BankAccountResponse } from '../../models/bank-account-response';

export interface Update11$Params {
  id: number;
      body: BankAccountRequest
}

export function update11(http: HttpClient, rootUrl: string, params: Update11$Params, context?: HttpContext): Observable<StrictHttpResponse<BankAccountResponse>> {
  const rb = new RequestBuilder(rootUrl, update11.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BankAccountResponse>;
    })
  );
}

update11.PATH = '/bank-account/{id}';
